# Generated by Django 5.0.2 on 2024-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='content',
            new_name='opis',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
        migrations.AddField(
            model_name='entry',
            name='obraz',
            field=models.ImageField(default=' ', upload_to='entry_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='tytul',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
