# Generated by Django 5.0.2 on 2024-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_author_entry_autor_rename_content_entry_opis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='opis',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='obraz',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tytul',
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
