# Generated by Django 5.0.2 on 2024-02-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_autor_entry_author_rename_opis_entry_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entry_photos/%Y/%m/%d/'),
        ),
    ]
